In [12]:
import pandas as pd

In [13]:
df = pd.read_excel("vendas_narastore.xlsx", usecols="A:G")
df

,Data,Vendedor,Produto,Categoria,Quantidade,Valor Unit. (R$),Total (R$)
0,10/03/2025,Ana Lima,Notebook Dell,Eletrônicos,1,3200.0,3200.0
1,10/03/2025,Carlos Souza,Mouse Sem Fio,Periféricos,3,89.9,269.7
2,11/03/2025,Beatriz Nunes,Cadeira Gamer,Móveis,2,750.0,1500.0
3,11/03/2025,Ana Lima,"Monitor 24""",Eletrônicos,1,980.0,980.0
4,12/03/2025,Diego Ferreira,Teclado Mecânico,Periféricos,2,320.0,640.0
5,12/03/2025,Carlos Souza,Headset Gamer,Periféricos,1,450.0,450.0
6,13/03/2025,Beatriz Nunes,Notebook Dell,Eletrônicos,1,3200.0,3200.0
7,13/03/2025,Diego Ferreira,Mesa de Escritório,Móveis,1,1200.0,1200.0
8,14/03/2025,Ana Lima,Mouse Sem Fio,Periféricos,5,89.9,449.5
9,14/03/2025,Carlos Souza,"Monitor 24""",Eletrônicos,2,980.0,1960.0
10,17/03/2025,Beatriz Nunes,Teclado Mecânico,Periféricos,3,320.0,960.0
11,17/03/2025,Diego Ferreira,Headset Gamer,Periféricos,2,450.0,900.0
12,18/03/2025,Ana Lima,Cadeira Gamer,Móveis,1,750.0,750.0
13,18/03/2025,Carlos Souza,Notebook Dell,Eletrônicos,1,3200.0,3200.0
14,19/03/2025,Beatriz Nunes,Mouse Sem Fio,Periféricos,4,89.9,359.6
15,19/03/2025,Diego Ferreira,"Monitor 24""",Eletrônicos,1,980.0,980.0
16,20/03/2025,Ana Lima,Mesa de Escritório,Móveis,2,1200.0,2400.0
17,20/03/2025,Carlos Souza,Teclado Mecânico,Periféricos,1,320.0,320.0
18,21/03/2025,Beatriz Nunes,Headset Gamer,Periféricos,3,450.0,1350.0
19,21/03/2025,Diego Ferreira,Notebook Dell,Eletrônicos,1,3200.0,3200.0

In [14]:
df = pd.read_excel(
    "vendas_narastore.xlsx", usecols=["Vendedor","Total (R$)"])  # usecols serve como um filtro para colunas, usando o nome ou a posição da coluna
df

          Vendedor  Total (R$)
0         Ana Lima      3200.0
1     Carlos Souza       269.7
2    Beatriz Nunes      1500.0
3         Ana Lima       980.0
4   Diego Ferreira       640.0
5     Carlos Souza       450.0
6    Beatriz Nunes      3200.0
7   Diego Ferreira      1200.0
8         Ana Lima       449.5
9     Carlos Souza      1960.0
10   Beatriz Nunes       960.0
11  Diego Ferreira       900.0
12        Ana Lima       750.0
13    Carlos Souza      3200.0
14   Beatriz Nunes       359.6
15  Diego Ferreira       980.0
16        Ana Lima      2400.0
17    Carlos Souza       320.0
18   Beatriz Nunes      1350.0
19  Diego Ferreira      3200.0

In [15]:
total = df["Total (R$)"].sum()
media = df["Total (R$)"].mean()
maximo = df["Total (R$)"].max()
minimo = df["Total (R$)"].min()

In [16]:
print(f'Total {total}')
print(f'Média {media}')
print(f'Máximo {maximo}')
print(f'Mínimo {minimo}')

Total 28268.800000000003
Média 1413.44
Máximo 3200.0
Mínimo 269.7