In [75]:
import pandas as pd
import numpy as np

In [76]:
df = pd.read_csv("funcionarios.csv", sep=';')
df

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar de Limpeza,Governança,"""2.139,00""",2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,"""1.746,00""",2021-12-29
2,3,1,Sara Teixeira,analista financeiro,Financeiro,"""5.356,00""",2022-03-01
3,4,1,Julia Monteiro,Auxiliar de Limpeza,Governança,"""2.070,00""",2019-06-10
4,5,1,Daniela Ramos,Auxiliar de Limpeza,Governança,"""1.572,00""",2018-10-16
...,...,...,...,...,...,...,...
129,130,12,Fernanda Cruz,Manutenção,Manutenção,"""2.221,00""",2020-08-16
130,131,12,Abel Correia,Gerente,Administração,"""8.404,00""",2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,"""2.700,00""",2021-01-22
132,133,12,Yuri Castro,segurança,Segurança,"""1.976,00""",2021-10-08
133,134,12,Eduardo Lopes,Recepcionista,Recepção,"""2.442,00""",2023-02-17

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  134 non-null    int64
 1   id_unidade      134 non-null    int64
 2   nome            134 non-null    str
 3   cargo           134 non-null    str
 4   departamento    134 non-null    str
 5   salario         128 non-null    str
 6   data_admissao   134 non-null    str
dtypes: int64(2), str(5)
memory usage: 7.5 KB

In [78]:
df.dtypes

id_funcionario    int64
id_unidade        int64
nome                str
cargo               str
departamento        str
salario             str
data_admissao       str
dtype: object

In [79]:
df.isnull().sum().reset_index()

            index  0
0  id_funcionario  0
1      id_unidade  0
2            nome  0
3           cargo  0
4    departamento  0
5         salario  6
6   data_admissao  0

In [80]:
df[df.isnull().any(axis=1)]

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
8,9,1,Bruno Costa,Auxiliar de Limpeza,Governança,NaN,2021-11-02
13,14,1,Yuri Castro,Analista Financeiro,Financeiro,NaN,2022-12-31
36,37,4,Larissa Sousa,cozinheiro,Alimentos e Bebidas,NaN,2019-09-29
42,43,4,Wilson Duarte,Analista Financeiro,Financeiro,NaN,2022-01-07
91,92,9,Wilson Duarte,Gerente,Administração,NaN,2024-02-29
103,104,10,Vanessa Cavalcanti,COZINHEIRO,Alimentos e Bebidas,NaN,2024-05-27

In [81]:
df[df.duplicated(subset=['nome','departamento', 'cargo'], keep=False)].sort_values(by='nome')

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar de Limpeza,Governança,"""2.139,00""",2020-10-05
45,46,5,Gabriela Lima,Auxiliar de Limpeza,Governança,"""1.702,00""",2023-05-01
31,32,3,Gabriela Lima,Auxiliar de Limpeza,Governança,"""1.538,00""",2020-08-28
84,85,9,Natalia Campos,Analista Financeiro,Financeiro,"""5.903,00""",2023-05-08
53,54,6,Natalia Campos,Analista Financeiro,Financeiro,"""5.601,00""",2022-12-26
65,66,6,Nicolas Cunha,Cozinheiro,Alimentos e Bebidas,"""3.255,00""",2020-02-13
15,16,2,Nicolas Cunha,Cozinheiro,Alimentos e Bebidas,"""3.208,00""",2024-02-01
82,83,8,Thiago Matos,Segurança,Segurança,"""1.840,00""",2023-04-26
46,47,5,Thiago Matos,Segurança,Segurança,"""2.051,00""",2019-07-31
33,34,4,Ursula Pinto,Manutenção,Manutenção,"""2.417,00""",2020-06-14
74,75,7,Ursula Pinto,Manutenção,Manutenção,"""2.090,00""",2019-06-24
116,117,11,Ursula Pinto,Manutenção,Manutenção,"""2.202,00""",2021-11-14
63,64,6,Wilson Duarte,Recepcionista,Recepção,"""2.636,00""",2022-02-22
6,7,1,Wilson Duarte,Recepcionista,Recepção,"""1.906,00""",2023-03-24
19,20,2,Yuri Castro,Segurança,Segurança,"""2.473,00""",2024-01-15
35,36,4,Yuri Castro,Segurança,Segurança,"""1.987,00""",2018-08-06
104,105,11,Yuri Castro,segurança,Segurança,"""1.853,00""",2020-03-20
132,133,12,Yuri Castro,segurança,Segurança,"""1.976,00""",2021-10-08
44,45,4,Zara Moraes,Segurança,Segurança,"""2.174,00""",2021-01-19
78,79,8,Zara Moraes,Recepcionista,Recepção,"""2.540,00""",2023-11-24
95,96,10,Zara Moraes,Segurança,Segurança,"""2.300,00""",2024-03-06
107,108,11,Zara Moraes,Recepcionista,Recepção,"""1.970,00""",2021-06-08

In [82]:
df['cargo'] = df['cargo'].str.strip().str.title()

In [83]:
df['cargo'].value_counts().reset_index()

                 cargo  count
0           Manutenção     24
1            Camareira     21
2            Segurança     20
3  Auxiliar De Limpeza     17
4        Recepcionista     15
5           Cozinheiro     15
6  Analista Financeiro     13
7              Gerente      9

In [84]:
df['departamento'].value_counts().reset_index()

          departamento  count
0           Governança     30
1           Manutenção     24
2            Segurança     20
3             Recepção     15
4           Financeiro     13
5  Alimentos e Bebidas     13
6                 Gov.      8
7        Administração      8
8                  A&B      2
9               Admin.      1

In [85]:
mapa = {
'Gov.':'Governança',
'Admin.':'Administração',
'A&B':'Alimentos e Bebidas',
}
df['departamento'] = df['departamento'].map(mapa).fillna(df['departamento'])

In [86]:
df['salario'] = df['salario'].astype(str)\
.str.replace('"','',regex=False)\
.str.replace("'"," ",regex=False)\
.str.replace('-','',regex=False)\
.str.replace(',','.',regex=False).str.strip().astype(float)

ValueError: could not convert string to float: '2.139.00'

In [ ]:
df

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  134 non-null    int64
 1   id_unidade      134 non-null    int64
 2   nome            134 non-null    str
 3   cargo           134 non-null    str
 4   departamento    134 non-null    str
 5   salario         128 non-null    float64
 6   data_admissao   134 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 7.5 KB

In [ ]:
df['data_admissao'] = pd.to_datetime(
    df['data_admissao'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

print('Tipo:', df['data_admissao'].dtype)
df.isnull().sum().reset_index()

Tipo: datetime64[us]

            index  0
0  id_funcionario  0
1      id_unidade  0
2            nome  0
3           cargo  0
4    departamento  0
5         salario  6
6   data_admissao  0