In [3]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv('pedidos_narashop.csv', sep=';')
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3
...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18

In [5]:
df['valor_pedido'] = df['quantidade'] * df['valor_unitario'] # 1
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_pedido
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12,490.05
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4,87.67
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
...,...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5,665.08
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4,7888.25
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18,197.10

In [6]:
df_fatura_categoria = df.groupby('categoria')['valor_pedido'].sum().reset_index().sort_values(by='valor_pedido', ascending=False) # 2


df_fatura_categoria

          categoria  valor_pedido
2       Eletrônicos   37037997.65
3          Esportes    8058234.35
1  Casa e Decoração    3333395.06
0        Brinquedos    2306126.65

In [7]:
df_3 = df.loc[(df['status_pedido'] == 'Entregue') & (df['valor_pedido'] > 500)] # 3
df_3

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_pedido
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
19,10020,Renato Cavalcante,Eletrônicos,Smartwatch,Entregue,3,461.46,3,1384.38
25,10026,Larissa Nunes,Brinquedos,Telescópio Infantil,Entregue,5,487.03,2,2435.15
...,...,...,...,...,...,...,...,...,...
19987,29988,Sérgio Machado,Casa e Decoração,Fritadeira Air Fryer,Entregue,5,403.51,8,2017.55
19989,29990,Diego Fernandes,Esportes,Bicicleta Ergométrica,Entregue,1,1235.61,10,1235.61
19992,29993,Larissa Nunes,Casa e Decoração,Tapete Sala,Entregue,3,279.57,18,838.71
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36

In [8]:
df_produto_valor_vendido = df.groupby('produto')['valor_pedido'].sum().reset_index().sort_values(by='valor_pedido', ascending= False) # 4


df_produto_valor_vendido.head()

                  produto  valor_pedido
27               Notebook   15091721.74
37               Smart TV    8474171.95
38             Smartphone    6806241.19
1   Bicicleta Ergométrica    5949159.26
40                 Tablet    3258725.63

In [9]:
array_produto_val_pedido = np.array(df_produto_valor_vendido['valor_pedido']) # 5

In [10]:
media = np.mean(array_produto_val_pedido)
mediana = np.median(array_produto_val_pedido)
q1 = np.percentile(array_produto_val_pedido, 25)
q3 = np.percentile(array_produto_val_pedido, 75)
distancia = round(((media - mediana) / mediana) * 100,2)

In [11]:
top_25_produto = df_produto_valor_vendido.loc[df_produto_valor_vendido['valor_pedido'] > q3]  #6
top_25_produto

                  produto  valor_pedido
27               Notebook   15091721.74
37               Smart TV    8474171.95
38             Smartphone    6806241.19
1   Bicicleta Ergométrica    5949159.26
40                 Tablet    3258725.63
39             Smartwatch    1344856.80
13   Fritadeira Air Fryer     980636.15
17        Jogo de Panelas     760544.58
36            SSD Externo     719921.59
45       Tênis de Corrida     696912.40
44    Telescópio Infantil     409588.10
43       Teclado Mecânico     372827.72

In [12]:
top_menos_25_produto = df_produto_valor_vendido.loc[df_produto_valor_vendido['valor_pedido'] < q1] # 6
top_menos_25_produto.sort_values(by='valor_pedido')

                     produto  valor_pedido
24       Massinha de Modelar      17550.06
9             Corda de Pular      23767.20
32            Porta-Retratos      26224.38
28    Organizador de Gavetas      36586.33
42            Tapete de Yoga      50209.91
30                   Pelúcia      51088.67
34  Quebra-Cabeça 1000 peças      51701.41
10         Difusor de Aromas      57532.21
14           Garrafa Térmica      63532.51
6        Carregador Portátil      64156.00
8        Conjunto de Toalhas      70889.32
0          Bermuda Esportiva      73266.61

In [19]:
array_total = np.array(df['valor_pedido'])
media_total = np.mean(array_total)
mediana_total = np.median(array_total)
dist = (media_total - mediana_total) / mediana_total
distancia_total = round(((media_total - mediana_total) / mediana_total) * 100,2)

In [21]:
print(f'Média total {media_total}')
print(f'Mediana total {mediana_total}')
print(f'A distancia entre a média e mediana é de {distancia_total} %. Nesse caso podemos ')

Média total 2536.7876855
Mediana total 882.635
A distancia entre a média e mediana é de 187.41 %. Nesse caso podemos

In [ ]:
# 1-  NaraShop - Produtos fora do padrão

In [ ]:
# 2 - Narashop - Vendedores fora do padrão