In [1]:
import pandas as pd

import numpy as np

In [37]:
df = pd.read_csv('pedidos_narashop.csv', sep=';' )
df.head()

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3

In [41]:
df['valor_pedido'] = df['quantidade'] * df['valor_unitario']  # 1
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_pedido
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12,490.05
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4,87.67
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
...,...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5,665.08
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4,7888.25
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18,197.10

In [46]:
df_faturamento_por_categoria = df.groupby("categoria")["valor_total"].sum().reset_index()
df_faturamento_por_categoria = df_faturamento_por_categoria.sort_values(by = "valor_pedido", ascending = False)  # 2
df_faturamento_por_categoria

KeyError: 'Column not found: valor_total'

In [30]:
pedidos_auditoria = df[(df["status_pedido"] == "Entregue") & (df["valor_pedido"] > 500)] # 3
pedidos_auditoria

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_total,valor_pedido
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80,18874.80
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06,1317.06
19,10020,Renato Cavalcante,Eletrônicos,Smartwatch,Entregue,3,461.46,3,1384.38,1384.38
25,10026,Larissa Nunes,Brinquedos,Telescópio Infantil,Entregue,5,487.03,2,2435.15,2435.15
...,...,...,...,...,...,...,...,...,...,...
19987,29988,Sérgio Machado,Casa e Decoração,Fritadeira Air Fryer,Entregue,5,403.51,8,2017.55,2017.55
19989,29990,Diego Fernandes,Esportes,Bicicleta Ergométrica,Entregue,1,1235.61,10,1235.61,1235.61
19992,29993,Larissa Nunes,Casa e Decoração,Tapete Sala,Entregue,3,279.57,18,838.71,838.71
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44,715.44
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36,578.36

In [43]:
df_produto_valor_vendido = df.groupby('produto')['valor_pedido'].sum().reset_index().sort_values(by = 'valor_pedido', ascending=False)  #4
df_produto_valor_vendido

                        produto  valor_pedido
27                     Notebook   15091721.74
37                     Smart TV    8474171.95
38                   Smartphone    6806241.19
1         Bicicleta Ergométrica    5949159.26
40                       Tablet    3258725.63
39                   Smartwatch    1344856.80
13         Fritadeira Air Fryer     980636.15
17              Jogo de Panelas     760544.58
36                  SSD Externo     719921.59
45             Tênis de Corrida     696912.40
44          Telescópio Infantil     409588.10
43             Teclado Mecânico     372827.72
21                LEGO Clássico     365791.62
4            Cafeteira Elétrica     362150.99
46              Violão Infantil     340633.78
5        Caixa de Som Bluetooth     287378.44
47                       Webcam     278877.33
7   Carrinho de Controle Remoto     277410.42
11            Espelho de Parede     276184.73
19                   Kettlebell     271850.88
41                  Tapete Sala     264729.81
12               Fone Bluetooth     264563.70
35      Raquete de Beach Tennis     259327.03
29                       Patins     233110.80
16                 Jogo de Cama     224794.69
15                     Halteres     200280.49
23                 Luva de Boxe     200234.01
20              Kit de Ciências     196385.59
31           Pista de Carrinhos     195027.74
25        Mochila de Hidratação     192107.97
22            Luminária de Mesa     189885.38
3             Boneca Articulada      93768.20
33            Quadro Decorativo      83236.49
2               Bola de Futebol      77586.08
26                Mouse Sem Fio      74555.56
18            Jogo de Tabuleiro      74070.26
0             Bermuda Esportiva      73266.61
8           Conjunto de Toalhas      70889.32
6           Carregador Portátil      64156.00
14              Garrafa Térmica      63532.51
10            Difusor de Aromas      57532.21
34     Quebra-Cabeça 1000 peças      51701.41
30                      Pelúcia      51088.67
42               Tapete de Yoga      50209.91
28       Organizador de Gavetas      36586.33
32               Porta-Retratos      26224.38
9                Corda de Pular      23767.20
24          Massinha de Modelar      17550.06