In [3]:
import pandas as pd
import numpy as np

In [8]:
df_clientes = pd.read_csv('naranerd_clientes.csv')
df_produtos = pd.read_csv('naranerd_produtos.csv')
df_vendedores = pd.read_csv('naranerd_vendedores.csv')
df_vendas = pd.read_csv('naranerd_vendas.csv')

In [9]:
df_clientes.head()

   id_cliente              nome                        email       cidade
0           1     Carla Correia     carla.correia1@email.com  Nova Iguaçu
1           2        João Gomes        joão.gomes2@email.com    Cabo Frio
2           3       Bruno Rocha       bruno.rocha3@email.com    Cabo Frio
3           4      Karina Souza      karina.souza4@email.com  São Gonçalo
4           5  Bernardo Freitas  bernardo.freitas5@email.com  Nova Iguaçu

In [13]:
df_clientes[['nome', 'cidade']]

                 nome              cidade
0       Carla Correia         Nova Iguaçu
1          João Gomes           Cabo Frio
2         Bruno Rocha           Cabo Frio
3        Karina Souza         São Gonçalo
4    Bernardo Freitas         Nova Iguaçu
..                ...                 ...
245      Ximena Souza       Volta Redonda
246    Gabriela Rocha      Rio de Janeiro
247      Camila Souza         Nova Iguaçu
248    Yasmin Correia  São João de Meriti
249   Thiago Teixeira       Volta Redonda

[250 rows x 2 columns]

In [10]:
df_produtos.head()

   id_produto                     nome categoria   preco
0           1   Console Retro Portátil     Games  300.19
1           2  Jogo Aventura Galáctica     Games   60.37
2           3     Controle sem Fio Pro     Games  269.95
3           4   Jogo RPG Reino Sombrio     Games  243.00
4           5         Headset Gamer X7     Games  289.56

In [15]:
# df_vendas[df_vendas['valor'] > 100][['id_produto', 'valor']]
df_vendas.loc[df_vendas['valor'] > 100][['id_produto', 'valor']]

      id_produto    valor
1             10   604.65
2             72   904.22
3             52  1446.04
5             57   457.93
6             45   378.31
...          ...      ...
5195           8   673.45
5196          53   583.78
5197          48   919.53
5198          79   337.77
5199          39   694.34

[4660 rows x 2 columns]

In [16]:
df_vendas.loc[(df_vendas['id_cliente'] == 3) & (df_vendas ['valor'] > 100)]

,id_venda,id_cliente,id_vendedor,id_produto,quantidade,valor,data_venda
1418,1419,3,5,27,3,945.08,2024-12-19
1621,1622,3,8,33,5,286.28,2024-07-25
2416,2417,3,6,30,3,1251.72,2024-02-14
2525,2526,3,8,77,1,207.12,2024-02-03
3742,3743,3,10,46,3,248.22,2024-12-19
4001,4002,3,7,48,5,1625.13,2024-09-25

In [20]:
df_vendas

,id_venda,id_cliente,id_vendedor,id_produto,quantidade,valor,data_venda
0,1,194,2,43,1,56.39,2024-05-27
1,2,245,6,10,2,604.65,2024-03-30
2,3,12,2,72,2,904.22,2024-09-27
3,4,91,11,52,5,1446.04,2024-01-16
4,5,31,4,43,2,98.36,2024-04-12
...,...,...,...,...,...,...,...
5195,5196,120,5,8,3,673.45,2024-06-05
5196,5197,132,3,53,2,583.78,2024-10-27
5197,5198,241,1,48,3,919.53,2024-05-25
5198,5199,67,5,79,3,337.77,2024-09-21
5199,5200,190,2,39,2,694.34,2024-09-18

In [24]:
qtd_loja = df_vendas.groupby('id_vendedor')['id_venda'].size().reset_index(name = 'qtde vendas')
qtd_loja.loc[qtd_loja['qtde vendas'] > 350]

qtd_loja

    id_vendedor  qtde vendas
0             1          343
1             2          338
2             3          370
3             4          332
4             5          354
5             6          341
6             7          363
7             8          345
8             9          330
9            10          348
10           11          358
11           12          335
12           13          369
13           14          328
14           15          346

In [11]:
df_vendedores.head()

   id_vendedor             nome                    loja
0            1   Eduardo Araújo  NaraNerd Norteshopping
1            2  Juliana Almeida         NaraNerd Online
2            3      Caio Araújo         NaraNerd Online
3            4     Rodrigo Lima  NaraNerd Norteshopping
4            5      André Souza         NaraNerd Centro

In [12]:
df_vendas.head()

,id_venda,id_cliente,id_vendedor,id_produto,quantidade,valor,data_venda
0,1,194,2,43,1,56.39,2024-05-27
1,2,245,6,10,2,604.65,2024-03-30
2,3,12,2,72,2,904.22,2024-09-27
3,4,91,11,52,5,1446.04,2024-01-16
4,5,31,4,43,2,98.36,2024-04-12

In [26]:
resultado = pd.merge(df_vendas, df_produtos,
 on='id_produto', how='inner')

resultado[['id_venda', 'data_venda', 'nome', 'categoria', 'valor']]

,id_venda,data_venda,nome,categoria,valor
0,1,2024-05-27,Jogo RPG Reino Sombrio (Edição Especial),Games,56.39
1,2,2024-03-30,Jogo Luta Arena Final,Games,604.65
2,3,2024-09-27,Action Figure Herói Cósmico (Edição Especial),Colecionáveis,904.22
3,4,2024-01-16,Jogo Aventura Galáctica (Edição Especial),Games,1446.04
4,5,2024-04-12,Jogo RPG Reino Sombrio (Edição Especial),Games,98.36
...,...,...,...,...,...
5195,5196,2024-06-05,Jogo Estratégia Império,Games,673.45
5196,5197,2024-10-27,Jogo Aventura Galáctica (Edição Especial),Games,583.78
5197,5198,2024-05-25,Jogo RPG Reino Sombrio (Edição Especial),Games,919.53
5198,5199,2024-09-21,Mangá Detetive das Sombras Vol.1 (Edição Espec...,Animes/Mangás,337.77
5199,5200,2024-09-18,Card Holográfico Raro (Edição Especial),Colecionáveis,694.34

In [30]:
resultado = pd.merge(df_vendas, df_produtos,
 on='id_produto', how='inner')

df_fat_cat = resultado.groupby('categoria')['valor'].sum().reset_index().sort_values(by='valor', ascending= False)

df_fat_cat.loc[df_fat_cat['valor'] > 60000]

             categoria       valor
2                Games  1196492.48
1        Colecionáveis   687718.76
3  Roupas e Acessórios   394625.60
0        Animes/Mangás   228345.50