In [52]:
import pandas as pd
import numpy as np

In [53]:
df_2024_1 = pd.read_csv('combust_2024.01.csv', sep=';', decimal=',')
df_2024_2 = pd.read_csv('combust_2024.02.csv', sep=';', decimal=',')
df_2025_1 = pd.read_csv('combust_2025.01.csv', sep=';', decimal=',')
df_2025_2 = pd.read_csv('combust_2025.02.csv', sep=';', decimal=',')

C:\Users\vitor.jsouza\AppData\Local\Temp\ipykernel_9204\1050854873.py:3: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Unidade de Medida, 13: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_1 = pd.read_csv('combust_2025.01.csv', sep=';', decimal=',')

In [54]:
df = pd.concat([df_2024_1, df_2024_2,df_2025_1, df_2025_2],ignore_index=True)

display(df.head())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
2,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,DIESEL S10,01/01/2024,5.93,NaN,R$ / litro,VIBRA
3,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,ETANOL,01/01/2024,3.99,NaN,R$ / litro,VIBRA
4,NE,AL,ARAPIRACA,AUTO POSTO SAO FRANCISCO LTDA,12.706.529/0001-04,RUA SAO FRANCISCO,274,NaN,CENTRO,57300-080,GASOLINA,01/01/2024,5.48,NaN,R$ / litro,VIBRA

In [55]:
df.columns

Index(['Regiao - Sigla', 'Estado - Sigla', 'Municipio', 'Revenda',
       'CNPJ da Revenda', 'Nome da Rua', 'Numero Rua', 'Complemento', 'Bairro',
       'Cep', 'Produto', 'Data da Coleta', 'Valor de Venda', 'Valor de Compra',
       'Unidade de Medida', 'Bandeira'],
      dtype='str')

### 02 - Gasolina comum RJ

In [56]:
df_gas_com = df.loc[df['Produto'] == 'GASOLINA']

In [57]:
df_gas_com_rj = df.loc[(df['Estado - Sigla'] == 'RJ') & (df['Produto'] == 'GASOLINA')]
df_gas_com_rj.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
122,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,GASOLINA,01/01/2024,5.99,NaN,R$ / litro,VIBRA
130,SE,RJ,CAMPOS DOS GOYTACAZES,ARARA FLUMINENSE COMERCIO DE COMBUSTIVEIS LTDA.,07.614.346/0004-71,AVENIDA ALBERTO TORRES,100,NaN,CENTRO,28010-117,GASOLINA,01/01/2024,5.99,NaN,R$ / litro,RAIZEN
131,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO SAO LUCAS DE CAMPOS LTDA,04.718.173/0001-09,"RODOVIA BR-101 KM 80,5",S/N,NaN,IBITIOCA,28120-000,GASOLINA,01/01/2024,5.89,NaN,R$ / litro,RAIZEN
133,SE,RJ,CAMPOS DOS GOYTACAZES,MOTO MERCANTIL CAMPISTA S A,28.935.153/0001-40,RUA DOS GOYTACAZES,342,NaN,CENTRO,28010-460,GASOLINA,01/01/2024,5.99,NaN,R$ / litro,VIBRA
136,SE,RJ,CAMPOS DOS GOYTACAZES,G.S. NOGUEIRA COMBUSTÍVEIS LTDA,03.784.646/0001-03,RUA JOAQUIM LORENA,6,NaN,URURAÍ,28020-230,GASOLINA,01/01/2024,5.79,NaN,R$ / litro,BRANCA

In [58]:
df_munic_gas_rj = df_gas_com_rj.groupby('Municipio')['Valor de Venda'].mean().reset_index().sort_values(by= 'Valor de Venda', ascending= False)
df_munic_gas_rj

                      Municipio  Valor de Venda
29                    TRES RIOS        6.591634
0                ANGRA DOS REIS        6.521620
18                   PETROPOLIS        6.479639
2                BARRA DO PIRAI        6.375640
11                        MACAE        6.364828
16                NOVA FRIBURGO        6.357044
10                    ITAPERUNA        6.352013
6         CAMPOS DOS GOYTACAZES        6.338306
5                     CABO FRIO        6.322089
23  SAO FRANCISCO DE ITABAPOANA        6.214804
31                VOLTA REDONDA        6.206265
1                      ARARUAMA        6.158700
27                    SAQUAREMA        6.133649
3                   BARRA MANSA        6.092928
30                      VALENCA        6.047609
26                     SAPUCAIA        5.994565
22       SANTO ANTONIO DE PADUA        5.962665
21               RIO DE JANEIRO        5.930698
13                       MARICA        5.899534
19                      RESENDE        5.885842
24                  SAO GONCALO        5.855353
20                   RIO BONITO        5.848639
8                      ITABORAI        5.842281
17                  NOVA IGUACU        5.807970
7               DUQUE DE CAXIAS        5.793860
25           SAO JOAO DE MERITI        5.780650
14                    NILOPOLIS        5.769526
15                      NITEROI        5.757424
4                  BELFORD ROXO        5.752965
12                         MAGE        5.615435
9                       ITAGUAI        5.602390
28                  TERESOPOLIS        5.508448

### 03 - Outliers de preço: Gasolina Comum no RJ

In [59]:
df_gas_com_post_rj = df_gas_com_rj.groupby('Revenda')['Valor de Venda'].mean().reset_index().sort_values(by= 'Valor de Venda', ascending= False)
df_gas_com_post_rj

                                               Revenda  Valor de Venda
690                        POSTO JARDIM OCEANICO LTDA.        7.750674
76   AUTO POSTO DE COMBUSTIVEIS M C 2000 DE SANTA I...        7.415000
776                        POSTO SATURNO FRIBURGO LTDA        6.824444
1                   A C TRANCOZO M B COMBUSTIVEIS LTDA        6.742157
304  COMERCIO DE PETROLEO E DERIVADOS COND DO RIO N...        6.713529
..                                                 ...             ...
668                             POSTO FLAMAREDI EIRELI        5.282000
571              POSTO DE GASOLINA JARDIM SULACAP LTDA        5.226364
569              POSTO DE GASOLINA JAGUAR DO ANIL LTDA        5.156667
567                     POSTO DE GASOLINA ITAJUBA LTDA        5.090000
560                        POSTO DE GASOLINA GALP LTDA        5.090000

[872 rows x 2 columns]

In [60]:
array_gas_com_post_rj = np.array(df_gas_com_post_rj['Valor de Venda'])
media = np.mean(array_gas_com_post_rj)
mediana = np.median(array_gas_com_post_rj)
q1 = np.percentile(array_gas_com_post_rj, 25)
q2 = np.percentile(array_gas_com_post_rj, 50)  
q3 = np.percentile(array_gas_com_post_rj, 75)
iqr = q3 - q1
limite_superior = q3 + (1.5 * iqr)
limite_inferior = q1 - (1.5 * iqr)

print(f'Média {media}')
print(f'Mediana {mediana}')
print(f'Q1: {q1}')
print(f'Q2: {q2}')
print(f'Q3: {q3}')
print(f'Limite Superior {limite_superior}')
print(f'Limite Inferior {limite_inferior}')

Média 5.947818265606212
Mediana 5.9136419461502125
Q1: 5.692154135338346
Q2: 5.9136419461502125
Q3: 6.19
Limite Superior 6.936768796992482
Limite Inferior 4.945385338345865

In [61]:
outlier_sup_gas_com_rj = df_gas_com_post_rj.loc[df_gas_com_post_rj['Valor de Venda'] > limite_superior]
outlier_sup_gas_com_rj

                                               Revenda  Valor de Venda
690                        POSTO JARDIM OCEANICO LTDA.        7.750674
76   AUTO POSTO DE COMBUSTIVEIS M C 2000 DE SANTA I...        7.415000

In [63]:
outlier_inf_gas_com_rj = df_gas_com_post_rj.loc[df_gas_com_post_rj['Valor de Venda'] < limite_inferior]
outlier_inf_gas_com_rj

Empty DataFrame
Columns: [Revenda, Valor de Venda]
Index: []

### 04 - Comparando estados: Etanol Hidratado

In [64]:
df_etanol = df.loc[df['Produto'] == 'ETANOL']
df_etanol_sp_rj = df_etanol.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index().sort_values(by= 'Valor de Venda', ascending= False)
df_etanol_sp_rj = df_etanol_sp_rj.loc[df_etanol_sp_rj['Estado - Sigla'].isin(['RJ', 'SP'])]
df_etanol_sp_rj

   Estado - Sigla  Valor de Venda
18             RJ        4.434487
25             SP        3.896279

In [ ]:
df_etanol_rj = df_etanol.loc[df_etanol['Estado - Sigla'] == 'RJ']
array_etanol_rj = np.array(df_etanol_rj)
q1 = np.percentile(array_gas_com_post_rj, 25)
q2 = np.percentile(array_gas_com_post_rj, 50)  
q3 = np.percentile(array_gas_com_post_rj, 75)
iqr = q3 - q1
limite_superior = q3 + (1.5 * iqr)
limite_inferior = q1 - (1.5 * iqr)